### PR TITLE
Write your own operator doc

### PR DESCRIPTION
**Pull request by dholbach**
Opening this as a draft pull request to address #11. I wrote a little bit of text for the doc, but found I'll need help to read the diff between the boilerplate code that's provided by `kubebuilder` and what we have in https://github.com/kubernetes-sigs/addon-operators/tree/master/coredns.

Any help to finish this would be much appreciated, as we'll need this doc to reach out, get more people to kick the tires and give us feedback.

Side-point: I was actually a bit surprised by how many files moved around. Could we make it so that the differences are somewhat smaller, so that reading the diff gets really clear and people who attempt to write their own addon operator will have to move things around a bit less? (It could also well be that I made a mistake along the way somewhere...) @justinsb @johnsonj

### CODE REVIEW

**Comment by johnsonj** [comment]
/reopen 

We should talk about this next meeting. This topic came up in our F2F at Kubecon.

**Comment by dholbach** [comment]
As far as I understood it, we wanted to tackle #24 first, so that the diff between v2 templates (now that all current patches are in [kubebuilder 2.2.0](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v2.2.0)) and our coredns operator are minimal and can be used as a basis for writing these docs.

E.g.
- install kubebuilder (>= min version)
- run these commands, delete irrelevant bits
- now we'll take you through the crucial bits of an example operator we wrote (highlight important sections in the diff mentioned above)
- demo section (how to run it)
- conclusion / next steps / join cluster addons meetings

Does that make sense?

**Comment by rajansandeep** [comment]
> Does that make sense?

@dholbach I think that makes sense.
If it's okay, I'd like to tackle #24 and update the existing coredns operator to v2 and then contribute to this draft based on the coredns operator.

**Comment by dholbach** [comment]
@rajansandeep That would be fantastic - I'm sure @johnsonj and @justinsb are happy about this too. :-)

**Comment by johnsonj** [comment]
sounds great to me!

**Pull request closed without merging**
