### PR TITLE
Example core-dns operator using declarative pattern

### PR DESCRIPTION
**Pull request by justinsb**
Strawman for discussion in meeting tomorrow!

cc @dholbach

### CODE REVIEW

**Comment by dholbach** [comment]
Thanks for your work on this @justinsb!

I tried playing around with this. Could it be that a `Dockerfile` is missing (`make docker-build`)?

**Comment by stealthybox** [comment]
I got it running
```
mkdir -p $GOPATH/src/sigs.k8s.io/
cd $GOPATH/src/sigs.k8s.io/
git clone git@github.com:kubernetes-sigs/addon-operators.git
hub checkout https://github.com/kubernetes-sigs/addon-operators/pull/7

export GO111MODULE=on
go mod download
go mod vendor

make
kind create cluster --image kindest/node:v1.14.0
make install
```

```
~/go/src/sigs.k8s.io/addon-operators/coredns strawman_coredns* 6s
❯ k get crd
NAME                    CREATED AT
coredns.addons.k8s.io   2019-04-30T15:43:43Z

~/go/src/sigs.k8s.io/addon-operators/coredns strawman_coredns*
❯ k get coredns.addons.k8s.io
No resources found.
```

**Comment by johnsonj** [comment]
I've added an example of Patch (as in kustomize patch) to this operator: https://github.com/justinsb/addon-operators/pull/1

**Comment by stealthybox** [comment]
/lgtm

@justinsb @johnsonj @dholbach :
I think we should merge this implementation.
I like that it works from a manifests as a starting point.
IMHO, we should work on making that backend pluggable next (ie: cluster bundle / git / ORAS).
That will move us toward tools and libs that can be used by cluster-management tools to install the operators/rbac as well.

@johnsonj maybe re-open justinsb#1 on this repo after we merge this?

**Comment by dholbach** [comment]
Can we merge this, or is there more feedback to be resolved first?

**Comment by atoato88** [comment]
I'm interested in this PR and checked that works on my env.
But this PR doesn't have a test like ["Golden File Tests"](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/master/docs/addon/walkthrough/tests.md#golden-file-tests).
I would like to add it after merged this PR, is it OK?

**Comment by johnsonj** [comment]
Sounds good to me!

**Comment by justinsb** [comment]
Removed the WIP label.  Does someone want to add lgtm and start our engines? :-)

**Comment by stealthybox** [comment]
> Does someone want to add lgtm and start our engines? :-)

Let the games begin! :tada: :boom:

**Comment by johnsonj** [comment]
awesome! 

/lgtm

**Pull request merged**
