### PR TITLE
Add SCL as approver/reviewer

### PR DESCRIPTION
**Pull request by dholbach**
Thanks Tim for the note (https://github.com/kubernetes/org/issues/630#issuecomment-474871018)

### CODE REVIEW

**Comment by dholbach** [comment]
(Not quite sure if I got it right...)

**Comment by dholbach** [comment]
@nikhita I guess with f4ad90abf6e7e26ae2fb96da456b586d782168a7 this PR is irrelevant now, right?

**Comment by nikhita** [comment]
> @nikhita I guess with f4ad90a this PR is irrelevant now, right?

Yeah, I figured it was just easier to push a commit (since the repo is new) than wait for approval. :)

/close

**Comment by dholbach** [comment]
Thanks @nikhita for your help with this!

**Pull request closed without merging**
